---
AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template to launch an EC2 instance

Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
    Description: EC2 instance type
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
    ConstraintDescription: Must be a valid EC2 instance type.

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-a4c7edb2
      InstanceType: !Ref InstanceType
      KeyName: cf-demo
      Tags:
        - Key: Name
          Value: MyEC2Instance-us2
