---
AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template to launch an EC2 instance

Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
    Description: EC2 instance type
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
    ConstraintDescription: Must be a valid EC2 instance type.
  Region:
    Type: String
    AllowedValues:
      - stage
      - us1
      - eu
      - us2
    Description: Select Region Type
    Default: us1
  
  Environment:
    Type: String
    AllowedValues:
      - stage
      - prod
    Description: Select which Type
    Default: prod

  ApplicationName:
    Type: String
    Description: Enter the name of the application
    Default: 'authzero'

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-a4c7edb2
      InstanceType: !Ref InstanceType
      KeyName: cf-demo
      Tags:
        - Key: Name
          Value: !Join [ '-', [!Ref Region, !Ref Environment, !Ref ApplicationName, "waf"]]
